### ISSUE TITLE
Model History APIs are not available from 9008 without using RPC

### ISSUE THREAD

**Issue by wmeddie** [SkymindIO/skil-clients#6]
The ModelHistory API comes from a ModelHistory server which listens on a separate port than the PLD.  So ModelHistory requests currently need to send login requests to port 9008 but then do model/minibatch/feedback requests to 9100, (or to the RPC /rpc/{modelHistoryServerId}/xxx)

The Swagger should be changed to prepend /rpc/{modelHistoryServerId} to all of the APIs.

**Comment by ShamsUlAzeem** [comment]
@wmeddie I'll test this out. Can you list the steps here to find out the modelHistoryServerId here?
